apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 30m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /liveness
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 1
          failureThreshold: 1
          successThreshold: 1